"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob, sys, os, os.path

# returns a list of all the files in a directory tree
def walk_dir(dirname):
  files = []
  ret = [ (dirname, files) ]
  for name in os.listdir(dirname):
    fullname = os.path.join(dirname, name)
    if os.path.isdir(fullname):
      ret.extend(walk_dir(fullname))
    else:
      files.append(fullname)
  return ret

options = {
'options': {
	'py2app':{
		'argv_emulation':False,
		'prefer_ppc':False,
		'app':['rewired server.py'],
		'plist': {'NSHumanReadableCopyright':'http://re-wired.info',
		'CFBundleIdentifier':         're:wired.Server'},
		'iconfile':			're-wired.icns',
		'includes':			['M2Crypto'],
	}
},
'name':				'reWired Server',
'version':			'20130402A2',
'description':		'The re:invented wired server',
'long_description':	'The re:invented wired server',
'author':			'docmeth02',
'author_email':		'http://re-wired.info',
'url':				'http://re-wired.info',
'packages':			['includes','rewiredserver'],
'scripts':			[],
'package_data':		{},
'data_files':		{'data' : walk_dir('data'), 'rewiredserver' : walk_dir('rewiredserver')},
'setup_requires':	['py2app','M2Crypto','dnspython'],
'platforms':		['i386', 'x86_64','ppc','ppc_64'],
}
setup(**options)
